# Generated by Django 3.0.2 on 2020-02-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_sensor',
            name='connectivity_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device_sensor',
            name='last_maintained_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device_sensor',
            name='last_maintained_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
