# Generated by Django 3.0.2 on 2020-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20200210_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.ImageField(upload_to='component_images'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_image',
            field=models.ImageField(upload_to='component_images'),
        ),
    ]
