# Generated by Django 2.2.6 on 2020-05-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20200512_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac_address',
            new_name='port_number',
        ),
    ]
