# Generated by Django 2.2.6 on 2020-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20200520_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_sensor',
            name='device_sensor_id',
            field=models.CharField(max_length=10),
        ),
    ]
