# Generated by Django 3.0.2 on 2020-02-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20200210_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_sensor',
            name='floor_location',
        ),
        migrations.AddField(
            model_name='device',
            name='floor_location',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
