# Generated by Django 2.2.6 on 2020-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20200525_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.IntegerField(choices=[(0, 'Earthquake'), (1, 'Fire'), (2, 'Flood')])),
                ('announcement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_identifier', models.CharField(max_length=3)),
                ('floor_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_maxedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.IntegerField(choices=[(0, 'Connected'), (1, 'Under Maintenance'), (2, 'Needs Maintenance'), (3, 'Inactive')], default=3),
        ),
    ]
