# Generated by Django 2.2.6 on 2020-05-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20200525_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='floor_location',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
