# Generated by Django 2.2.6 on 2020-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20200418_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.IntegerField(choices=[(0, 'Connected'), (1, 'Inactive'), (2, 'Under Maintenance'), (3, 'Needs Maintenance')]),
        ),
    ]
