# Generated by Django 2.2.6 on 2020-05-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20200525_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='device_sensor_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
