# Generated by Django 2.2.6 on 2020-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20200525_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(default=0),
        ),
    ]
