# Generated by Django 2.2.6 on 2020-04-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20200418_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(choices=[('SEN_ACCEL', 'Triple Axis Accelerometer'), ('SEN_FLAME', 'Flame Sensor'), ('SEN_ULTRA', 'Ultrasonic Transducer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.IntegerField(choices=[(0, 'Fire'), (1, 'Flood'), (2, 'Earthquake')]),
        ),
    ]
