# Generated by Django 2.2.6 on 2020-04-18 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0008_auto_20200418_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=10, unique=True)),
                ('component_name', models.CharField(max_length=50)),
                ('component_type', models.IntegerField(choices=[(0, 'SEN - Fire'), (1, 'SEN - Flood'), (2, 'SEN - Earthquake'), (3, 'DEV - Others')])),
                ('component_image', models.ImageField(upload_to='component_images')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.IntegerField(choices=[(1, 'Connected'), (2, 'Inactive'), (3, 'Under Maintenance'), (4, 'Needs Maintenance')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ComponentConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=10, unique=True)),
                ('device_id', models.CharField(max_length=50)),
                ('sensor_id', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Connected'), (1, 'Inactive'), (2, 'Under Maintenance'), (3, 'Needs Maintenance')], max_length=1)),
                ('connectivity_status', models.BooleanField(default=True)),
                ('floor_location', models.IntegerField(choices=[(1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Fourth Floor')], max_length=1)),
                ('last_maintained_datetime', models.DateTimeField(default=None, null=True)),
                ('last_maintained_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
