# Generated by Django 2.2.6 on 2020-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_auto_20200418_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='componentconnection',
            name='connection_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
