# Generated by Django 2.2.6 on 2020-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20200418_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_sensor',
            name='floor_location',
            field=models.IntegerField(choices=[(1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Fourth Floor')], default=1),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.IntegerField(choices=[(0, 'Fire'), (1, 'Flood'), (2, 'Earthquake')]),
        ),
    ]
