# Generated by Django 2.2.6 on 2020-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_auto_20200419_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_image',
            field=models.ImageField(default='default.png', upload_to='component_images'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_image',
            field=models.ImageField(default='default.png', upload_to='component_images'),
        ),
    ]
