# Generated by Django 2.2.6 on 2020-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20200419_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='floor_location',
            field=models.IntegerField(default=1),
        ),
    ]
