# Generated by Django 2.2.6 on 2020-04-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20200419_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_sensor',
            name='sensor_status',
            field=models.IntegerField(choices=[(0, 'Connected'), (1, 'Inactive'), (2, 'Under Maintenance'), (3, 'Needs Maintenance')], default=0),
        ),
    ]
