# Generated by Django 2.2.6 on 2020-04-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_device_sensor_sensor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.IntegerField(choices=[(0, 'Fire'), (1, 'Flood'), (2, 'Earthquake')]),
        ),
    ]
