# Generated by Django 2.2.6 on 2020-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0018_auto_20200419_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='floor_location',
            field=models.IntegerField(choices=[('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor')], default=1),
        ),
    ]
