# Generated by Django 2.2.6 on 2020-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_auto_20200419_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='floor_location',
            field=models.IntegerField(choices=[(1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Fourth Floor')], default=1),
        ),
    ]
