# Generated by Django 2.2.6 on 2020-04-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0021_auto_20200419_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_image',
            field=models.ImageField(default='component_images/default.png', upload_to='component_images'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_image',
            field=models.ImageField(default='component_images/default.png', upload_to='component_images'),
        ),
    ]
