# Generated by Django 2.2.6 on 2020-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_auto_20200419_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_details',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.IntegerField(choices=[(0, 'Connected'), (1, 'Under Maintenance'), (2, 'Needs Maintenance'), (3, 'Inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='sensor_status',
            field=models.IntegerField(choices=[(0, 'Connected'), (1, 'Under Maintenance'), (2, 'Needs Maintenance'), (3, 'Inactive')], default=0),
        ),
    ]
