# Generated by Django 2.2.6 on 2020-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_auto_20200420_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_details',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
