# Generated by Django 2.2.6 on 2020-04-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_auto_20200420_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_Link',
            field=models.CharField(default='Link', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='device_productID',
            field=models.CharField(default='Product ID', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_dataType',
            field=models.CharField(default='Data Type', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_link',
            field=models.CharField(default='Link', max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_productID',
            field=models.CharField(default='Product ID', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_voltage',
            field=models.CharField(default='Voltage', max_length=50),
        ),
    ]
