# Generated by Django 2.2.6 on 2020-04-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_auto_20200420_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_dataType',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_data',
            field=models.CharField(default='Data', max_length=50),
        ),
    ]
