# Generated by Django 2.2.6 on 2020-04-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_auto_20200420_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device_sensor',
            name='cdevice_sensor_isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
