# Generated by Django 2.2.6 on 2020-04-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0028_auto_20200420_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_sensor',
            old_name='cdevice_sensor_isDeleted',
            new_name='device_sensor_isDeleted',
        ),
    ]
