# Generated by Django 2.2.6 on 2020-04-19 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0029_auto_20200420_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_maintained_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='last_maintained_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
