# Generated by Django 2.2.6 on 2020-04-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0030_auto_20200420_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_Link',
            new_name='device_link',
        ),
    ]
