# Generated by Django 2.2.6 on 2020-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0033_auto_20200420_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_image',
            field=models.ImageField(upload_to='component_images'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_image',
            field=models.ImageField(upload_to='component_images'),
        ),
    ]
