# Generated by Django 2.2.6 on 2020-04-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0034_auto_20200421_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_sensor',
            name='device_sensor_id',
            field=models.CharField(max_length=10),
        ),
    ]
