# Generated by Django 2.2.6 on 2020-05-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0035_auto_20200422_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_sensor',
            name='device_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='sensor_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
