# Generated by Django 2.2.6 on 2020-05-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0036_auto_20200504_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_sensor',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.Device'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.Sensor'),
        ),
    ]
