# Generated by Django 2.2.6 on 2020-05-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0037_auto_20200504_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_sensor',
            name='device_sensor_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
