# Generated by Django 2.2.6 on 2020-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='audit_isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='audit_type',
            field=models.IntegerField(choices=[(0, 'Component Logs'), (1, 'User Logs'), (2, 'Maintenance Logs')]),
        ),
    ]
