# Generated by Django 3.0.5 on 2020-05-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_device_device_type'),
        ('reports', '0002_auto_20200512_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='device_sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.Device'),
        ),
    ]
