# Generated by Django 2.2.6 on 2020-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_incident_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='details',
            field=models.CharField(default='details', max_length=100),
        ),
    ]
