# Generated by Django 2.2.6 on 2020-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auditlogs_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='audit_type',
            field=models.IntegerField(choices=[(0, 'Component Logs'), (1, 'User Logs'), (2, 'Maintenance Logs')], default=0, max_length=1),
        ),
    ]
