# Generated by Django 2.2.6 on 2020-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auditlogs_audit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='audit_type',
            field=models.IntegerField(choices=[(0, 'Component Logs'), (1, 'User Logs'), (2, 'Maintenance Logs')], default=0),
        ),
    ]
