# Generated by Django 2.2.6 on 2020-05-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200504_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlogs',
            old_name='details',
            new_name='audit_detail',
        ),
        migrations.RemoveField(
            model_name='auditlogs',
            name='audit_type',
        ),
    ]
