# Generated by Django 2.2.6 on 2020-05-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200504_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlogs',
            old_name='audit_detail',
            new_name='details',
        ),
    ]
