# Generated by Django 2.2.6 on 2020-05-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auditlogs_audit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlogs',
            old_name='details',
            new_name='audit_details',
        ),
    ]
