# Generated by Django 2.2.6 on 2020-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=50)),
            ],
        ),
    ]
