# Generated by Django 2.2.6 on 2020-04-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='job_position',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
