# Generated by Django 2.2.6 on 2020-04-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='user_images\\default.png', upload_to='user_images'),
        ),
    ]
