# Generated by Django 3.0.5 on 2020-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200525_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='position_isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
